#!/usr/bin/python3
import sys

if __name__ == "__main__":
    argc = len(sys.argv)
    if argc == 1:
        print("{} arguments.".format(argc - 1))
    if argc == 2:
        print("{} argument: \n{}: {}".format(argc - 1, argc - 1, sys.argv))
    else:
        print("{} arguments: \n{}: {}".format(argc - 1, argc - 1, sys.argv))
